import type { Metadata } from "next";
import {PT_Sans} from 'next/font/google';
import "./globals.css";
import Header from '@/app/_components/header';
import Footer from '@/app/_components/footer';

const ptSans = PT_Sans({weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSans.className} min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
